baseURL = "https://raghul-ravi1720.github.io/PersonalBlog/"

title = "Raghul 's Blog"
theme = "m10c"
[params]
  author = "Raghul Ravi"
  description = "A blog about all things technical."
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/raghul-ravi1720"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_ChrisJHart"
